import { randomBytes } from 'node:crypto';
import { access, mkdir, readFile, writeFile } from 'node:fs/promises';
import { constants as fsConstants } from 'node:fs';
import { existsSync } from 'node:fs';
import path from 'node:path';

import { createOpenClawClient, getOpenClawConfigFromEnv } from './openclaw-client';
import { commandExists } from './openclaw-command';

export type OpenClawProviderMode =
  | 'openai-api-key'
  | 'openai-codex'
  | 'anthropic-api-key'
  | 'anthropic-setup-token';

export interface OpenClawProviderMetadata {
  provider: OpenClawProviderMode;
  inlineEnvKey?: 'OPENAI_API_KEY' | 'ANTHROPIC_API_KEY';
  defaultModel?: string;
  authHint?: string;
}

export interface OpenClawSetupOptions {
  projectDir: string;
  envFile?: string;
  envExampleFile?: string;
  wrapperFile?: string;
  packageJsonFile?: string;
  provider?: OpenClawProviderMode;
  openclawCmd?: string;
  gatewayHost?: string;
  gatewayPort?: number;
  gatewayToken?: string;
  agentId?: string;
  model?: string;
  providerSecret?: string;
  autoStart?: boolean;
  overwriteWrapper?: boolean;
  updatePackageJsonScripts?: boolean;
}

export interface OpenClawSetupResult {
  projectDir: string;
  envFile: string;
  envExampleFile: string;
  wrapperFile: string;
  packageJsonFile: string;
  provider: OpenClawProviderMode;
  gatewayUrl: string;
  gatewayToken: string;
  agentId: string;
  model: string;
  authHint?: string;
  createdFiles: string[];
  updatedFiles: string[];
  skippedFiles: string[];
  warnings: string[];
  nextSteps: string[];
}

export interface OpenClawDoctorCheck {
  id: string;
  status: 'ok' | 'warn' | 'fail';
  message: string;
}

export interface OpenClawDoctorResult {
  ok: boolean;
  checks: OpenClawDoctorCheck[];
  authHint?: string;
}

const GENERATED_MARKER = '// Generated by @zootopiafresh/agent-core openclaw init';

function quoteEnvValue(value: string) {
  return JSON.stringify(value);
}

function parseDotEnv(content: string) {
  const result: Record<string, string> = {};

  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }

    const match = trimmed.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
    if (!match) {
      continue;
    }

    const [, key, rawValue] = match;
    const value = rawValue.trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      result[key] = value.slice(1, -1);
      continue;
    }

    result[key] = value;
  }

  return result;
}

async function readTextIfExists(filePath: string) {
  try {
    return await readFile(filePath, 'utf-8');
  } catch (error: any) {
    if (error?.code === 'ENOENT') {
      return null;
    }
    throw error;
  }
}

async function fileExists(filePath: string) {
  try {
    await access(filePath, fsConstants.F_OK);
    return true;
  } catch {
    return false;
  }
}

function upsertEnvContent(existingContent: string | null, updates: Record<string, string>) {
  const lines = (existingContent ?? '').split(/\r?\n/);
  const nextLines = [...lines];

  for (const [key, value] of Object.entries(updates)) {
    const nextLine = `${key}=${quoteEnvValue(value)}`;
    const index = nextLines.findIndex((line) => line.startsWith(`${key}=`));
    if (index >= 0) {
      nextLines[index] = nextLine;
    } else {
      if (nextLines.length > 0 && nextLines.at(-1)?.trim() !== '') {
        nextLines.push('');
      }
      nextLines.push(nextLine);
    }
  }

  return nextLines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}

function buildEnvExampleContent(
  providerMetadata: OpenClawProviderMetadata,
  gatewayUrl: string,
  gatewayHost: string,
  gatewayPort: number,
  agentId: string,
  provider: OpenClawProviderMode,
  model: string
) {
  const lines = [
    `OPENCLAW_URL=${gatewayUrl}`,
    `OPENCLAW_GATEWAY_HOST=${gatewayHost}`,
    `OPENCLAW_GATEWAY_PORT=${gatewayPort}`,
    'OPENCLAW_GATEWAY_TOKEN=',
    `OPENCLAW_AGENT_ID=${agentId}`,
    `OPENCLAW_PROVIDER_MODE=${provider}`,
    `OPENCLAW_PRIMARY_MODEL=${model}`,
  ];

  if (providerMetadata.inlineEnvKey) {
    lines.push(`${providerMetadata.inlineEnvKey}=`);
  }

  return `${lines.join('\n')}\n`;
}

function parseGatewayUrl(rawUrl: string) {
  try {
    return new URL(rawUrl);
  } catch {
    return null;
  }
}

function detectPackageManager(projectDir: string) {
  if (existsSync(path.join(projectDir, 'pnpm-lock.yaml'))) {
    return 'pnpm';
  }
  if (existsSync(path.join(projectDir, 'yarn.lock'))) {
    return 'yarn';
  }
  return 'npm';
}

function createWrapperScriptContent() {
  return `#!/usr/bin/env node
${GENERATED_MARKER}
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import {
  createOpenClawRunner,
  resolveOpenClawRunnerConfig,
} from '@zootopiafresh/agent-core/openclaw';

const projectDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)));
const config = resolveOpenClawRunnerConfig({
  appCommand: process.argv.slice(2),
  gatewayCmdDefault: process.env.OPENCLAW_CMD || 'openclaw',
  projectDir,
});

const runner = createOpenClawRunner(config);
runner.attachProcessHandlers();
await runner.start();
`;
}

async function writeManagedFile(
  filePath: string,
  content: string,
  options: { overwriteGeneratedOnly?: boolean } = {}
) {
  const existing = await readTextIfExists(filePath);

  if (existing !== null) {
    if (existing === content) {
      return 'unchanged' as const;
    }

    if (options.overwriteGeneratedOnly && !existing.includes(GENERATED_MARKER)) {
      return 'skipped' as const;
    }
  }

  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, content, 'utf-8');
  return existing === null ? ('created' as const) : ('updated' as const);
}

function updatePackageJsonScriptsContent(content: string, packageManager: string) {
  const parsed = JSON.parse(content) as {
    scripts?: Record<string, string>;
  };

  parsed.scripts ??= {};
  const next = { ...parsed.scripts };
  let changed = false;

  if (!next['openclaw:doctor']) {
    next['openclaw:doctor'] = 'agent-core openclaw doctor';
    changed = true;
  }

  if (!next['dev:with-gateway'] && next.dev) {
    const packageManagerDev =
      packageManager === 'yarn'
        ? 'yarn dev'
        : packageManager === 'pnpm'
          ? 'pnpm dev'
          : 'npm run dev';
    next['dev:with-gateway'] =
      `node --env-file=.env ./run-with-openclaw.mjs ${packageManagerDev}`;
    changed = true;
  }

  if (!next['start:with-gateway'] && next.start) {
    const packageManagerStart =
      packageManager === 'yarn'
        ? 'yarn start'
        : packageManager === 'pnpm'
          ? 'pnpm start'
          : 'npm run start';
    next['start:with-gateway'] =
      `node --env-file=.env ./run-with-openclaw.mjs ${packageManagerStart}`;
    changed = true;
  }

  if (!changed) {
    return null;
  }

  parsed.scripts = next;
  return `${JSON.stringify(parsed, null, 2)}\n`;
}

function resolveProviderSecret(
  providerMetadata: OpenClawProviderMetadata,
  existingEnv: Record<string, string>,
  explicitSecret?: string
) {
  if (!providerMetadata.inlineEnvKey) {
    return undefined;
  }

  return explicitSecret || process.env[providerMetadata.inlineEnvKey] || existingEnv[providerMetadata.inlineEnvKey];
}

export function generateOpenClawSecret(byteCount = 16) {
  return randomBytes(byteCount).toString('hex');
}

export function getOpenClawProviderMetadata(
  provider: OpenClawProviderMode,
  openclawCmd = 'openclaw'
): OpenClawProviderMetadata {
  switch (provider) {
    case 'openai-api-key':
      return {
        provider,
        inlineEnvKey: 'OPENAI_API_KEY',
        defaultModel: 'openai/gpt-5.4',
      };
    case 'openai-codex':
      return {
        provider,
        defaultModel: 'openai-codex/gpt-5.4',
        authHint: `${openclawCmd} models auth login --provider openai-codex`,
      };
    case 'anthropic-api-key':
      return {
        provider,
        inlineEnvKey: 'ANTHROPIC_API_KEY',
      };
    case 'anthropic-setup-token':
      return {
        provider,
      };
    default:
      throw new Error(`지원하지 않는 OpenClaw provider입니다: ${provider}`);
  }
}

export async function setupOpenClawProject(
  options: OpenClawSetupOptions
): Promise<OpenClawSetupResult> {
  const projectDir = path.resolve(options.projectDir);
  const envFile = options.envFile || path.join(projectDir, '.env');
  const envExampleFile = options.envExampleFile || path.join(projectDir, '.env.example');
  const wrapperFile = options.wrapperFile || path.join(projectDir, 'run-with-openclaw.mjs');
  const packageJsonFile = options.packageJsonFile || path.join(projectDir, 'package.json');
  const provider = options.provider || 'openai-api-key';
  const openclawCmd = options.openclawCmd || 'openclaw';
  const gatewayHost = options.gatewayHost || '127.0.0.1';
  const gatewayPort = options.gatewayPort || 18789;
  const agentId = options.agentId || 'main';
  const providerMetadata = getOpenClawProviderMetadata(provider, openclawCmd);
  const existingEnvContent = await readTextIfExists(envFile);
  const existingEnv = parseDotEnv(existingEnvContent ?? '');
  const gatewayToken =
    options.gatewayToken ||
    existingEnv.OPENCLAW_GATEWAY_TOKEN ||
    generateOpenClawSecret();
  const model = options.model || existingEnv.OPENCLAW_PRIMARY_MODEL || providerMetadata.defaultModel || 'openclaw';
  const gatewayUrl = `http://${gatewayHost}:${gatewayPort}`;
  const providerSecret = resolveProviderSecret(providerMetadata, existingEnv, options.providerSecret);
  const createdFiles: string[] = [];
  const updatedFiles: string[] = [];
  const skippedFiles: string[] = [];
  const warnings: string[] = [];

  const envUpdates: Record<string, string> = {
    OPENCLAW_URL: gatewayUrl,
    OPENCLAW_GATEWAY_HOST: gatewayHost,
    OPENCLAW_GATEWAY_PORT: String(gatewayPort),
    OPENCLAW_GATEWAY_TOKEN: gatewayToken,
    OPENCLAW_AGENT_ID: agentId,
    OPENCLAW_PROVIDER_MODE: provider,
    OPENCLAW_PRIMARY_MODEL: model,
  };

  if (providerSecret && providerMetadata.inlineEnvKey) {
    envUpdates[providerMetadata.inlineEnvKey] = providerSecret;
  }

  if (!providerSecret && providerMetadata.inlineEnvKey) {
    warnings.push(`${providerMetadata.inlineEnvKey} 값이 없어 .env에는 placeholder만 남깁니다.`);
  }

  const nextEnvContent = upsertEnvContent(existingEnvContent, envUpdates);
  const envWrite = await writeManagedFile(envFile, nextEnvContent);
  if (envWrite === 'created') createdFiles.push(envFile);
  if (envWrite === 'updated') updatedFiles.push(envFile);

  const envExampleContent = buildEnvExampleContent(
    providerMetadata,
    gatewayUrl,
    gatewayHost,
    gatewayPort,
    agentId,
    provider,
    model
  );
  const envExampleWrite = await writeManagedFile(envExampleFile, envExampleContent);
  if (envExampleWrite === 'created') createdFiles.push(envExampleFile);
  if (envExampleWrite === 'updated') updatedFiles.push(envExampleFile);

  const wrapperWrite = await writeManagedFile(wrapperFile, createWrapperScriptContent(), {
    overwriteGeneratedOnly: !options.overwriteWrapper,
  });
  if (wrapperWrite === 'created') createdFiles.push(wrapperFile);
  if (wrapperWrite === 'updated') updatedFiles.push(wrapperFile);
  if (wrapperWrite === 'skipped') {
    skippedFiles.push(wrapperFile);
    warnings.push('기존 run-with-openclaw.mjs가 사용자가 만든 파일이라 자동 덮어쓰기를 건너뛰었습니다.');
  }

  if (options.updatePackageJsonScripts !== false && (await fileExists(packageJsonFile))) {
    const packageJsonContent = await readFile(packageJsonFile, 'utf-8');
    const nextPackageJson = updatePackageJsonScriptsContent(
      packageJsonContent,
      detectPackageManager(projectDir)
    );
    if (nextPackageJson) {
      const packageJsonWrite = await writeManagedFile(packageJsonFile, nextPackageJson);
      if (packageJsonWrite === 'created') createdFiles.push(packageJsonFile);
      if (packageJsonWrite === 'updated') updatedFiles.push(packageJsonFile);
    }
  }

  const packageManager = detectPackageManager(projectDir);
  const nextSteps = [
    providerMetadata.authHint ? `추가 인증: ${providerMetadata.authHint}` : null,
    `환경 파일 확인: ${envFile}`,
    '설정 검증: agent-core openclaw doctor',
    `Gateway 포함 실행: node --env-file=.env ./run-with-openclaw.mjs ${packageManager === 'yarn' ? 'yarn dev' : packageManager === 'pnpm' ? 'pnpm dev' : 'npm run dev'}`,
  ].filter((item): item is string => Boolean(item));

  return {
    projectDir,
    envFile,
    envExampleFile,
    wrapperFile,
    packageJsonFile,
    provider,
    gatewayUrl,
    gatewayToken,
    agentId,
    model,
    authHint: providerMetadata.authHint,
    createdFiles,
    updatedFiles,
    skippedFiles,
    warnings,
    nextSteps,
  };
}

export async function doctorOpenClawProject(
  options: Pick<
    OpenClawSetupOptions,
    'projectDir' | 'envFile' | 'wrapperFile' | 'provider' | 'openclawCmd'
  > = { projectDir: process.cwd() }
): Promise<OpenClawDoctorResult> {
  const projectDir = path.resolve(options.projectDir);
  const envFile = options.envFile || path.join(projectDir, '.env');
  const wrapperFile = options.wrapperFile || path.join(projectDir, 'run-with-openclaw.mjs');
  const envContent = await readTextIfExists(envFile);
  const envValues = parseDotEnv(envContent ?? '');
  const openclawCmd = envValues.OPENCLAW_CMD || options.openclawCmd || 'openclaw';
  const provider = (options.provider || envValues.OPENCLAW_PROVIDER_MODE || 'openai-api-key') as OpenClawProviderMode;
  const providerMetadata = getOpenClawProviderMetadata(provider, openclawCmd);
  const checks: OpenClawDoctorCheck[] = [];
  const gatewayUrl = envValues.OPENCLAW_URL;
  const parsedGatewayUrl = gatewayUrl ? parseGatewayUrl(gatewayUrl) : null;

  checks.push({
    id: 'openclaw-cmd',
    status: commandExists(openclawCmd) ? 'ok' : 'fail',
    message: commandExists(openclawCmd)
      ? `OpenClaw 실행 파일을 찾았습니다: ${openclawCmd}`
      : `OpenClaw 실행 파일을 찾지 못했습니다: ${openclawCmd}`,
  });

  checks.push({
    id: 'env-file',
    status: envContent ? 'ok' : 'fail',
    message: envContent ? `.env 파일을 찾았습니다: ${envFile}` : `.env 파일이 없습니다: ${envFile}`,
  });

  checks.push({
    id: 'OPENCLAW_URL',
    status: !gatewayUrl ? 'fail' : parsedGatewayUrl ? 'ok' : 'fail',
    message: !gatewayUrl
      ? 'OPENCLAW_URL 설정이 없습니다.'
      : parsedGatewayUrl
        ? `OPENCLAW_URL 설정이 있습니다: ${gatewayUrl}`
        : `OPENCLAW_URL 값이 올바른 URL이 아닙니다: ${gatewayUrl}`,
  });

  for (const key of ['OPENCLAW_GATEWAY_HOST', 'OPENCLAW_GATEWAY_PORT', 'OPENCLAW_GATEWAY_TOKEN', 'OPENCLAW_AGENT_ID']) {
    checks.push({
      id: key,
      status: envValues[key] ? 'ok' : key === 'OPENCLAW_GATEWAY_TOKEN' || key === 'OPENCLAW_AGENT_ID' ? 'fail' : 'warn',
      message: envValues[key] ? `${key} 설정이 있습니다.` : `${key} 설정이 없습니다.`,
    });
  }

  if (parsedGatewayUrl && envValues.OPENCLAW_GATEWAY_PORT) {
    const urlPort =
      parsedGatewayUrl.port ||
      (parsedGatewayUrl.protocol === 'https:' ? '443' : parsedGatewayUrl.protocol === 'http:' ? '80' : '');
    if (urlPort && urlPort !== envValues.OPENCLAW_GATEWAY_PORT) {
      checks.push({
        id: 'gateway-port-match',
        status: 'warn',
        message: `OPENCLAW_URL의 포트(${urlPort})와 OPENCLAW_GATEWAY_PORT(${envValues.OPENCLAW_GATEWAY_PORT})가 다릅니다.`,
      });
    }
  }

  if (parsedGatewayUrl && envValues.OPENCLAW_GATEWAY_HOST) {
    if (parsedGatewayUrl.hostname !== envValues.OPENCLAW_GATEWAY_HOST) {
      checks.push({
        id: 'gateway-host-match',
        status: 'warn',
        message: `OPENCLAW_URL의 host(${parsedGatewayUrl.hostname})와 OPENCLAW_GATEWAY_HOST(${envValues.OPENCLAW_GATEWAY_HOST})가 다릅니다.`,
      });
    }
  }

  if (providerMetadata.inlineEnvKey) {
    checks.push({
      id: providerMetadata.inlineEnvKey,
      status: envValues[providerMetadata.inlineEnvKey] || process.env[providerMetadata.inlineEnvKey] ? 'ok' : 'warn',
      message:
        envValues[providerMetadata.inlineEnvKey] || process.env[providerMetadata.inlineEnvKey]
          ? `${providerMetadata.inlineEnvKey} 값이 있습니다.`
          : `${providerMetadata.inlineEnvKey} 값이 없습니다.`,
    });
  } else if (providerMetadata.authHint) {
    checks.push({
      id: 'provider-auth',
      status: 'warn',
      message: `추가 provider 인증이 필요할 수 있습니다: ${providerMetadata.authHint}`,
    });
  }

  checks.push({
    id: 'wrapper-file',
    status: (await fileExists(wrapperFile)) ? 'ok' : 'warn',
    message: (await fileExists(wrapperFile))
      ? `run-with-openclaw wrapper가 있습니다: ${wrapperFile}`
      : `run-with-openclaw wrapper가 없습니다: ${wrapperFile}`,
  });

  if (envValues.OPENCLAW_URL && envValues.OPENCLAW_GATEWAY_TOKEN) {
    const client = createOpenClawClient(
      getOpenClawConfigFromEnv({
        ...process.env,
        OPENCLAW_URL: envValues.OPENCLAW_URL,
        OPENCLAW_GATEWAY_TOKEN: envValues.OPENCLAW_GATEWAY_TOKEN,
        OPENCLAW_AGENT_ID: envValues.OPENCLAW_AGENT_ID || 'main',
      })
    );
    const gatewayCheck = await client.checkConnection();
    checks.push({
      id: 'gateway-health',
      status:
        gatewayCheck.code === 'ok'
          ? 'ok'
          : gatewayCheck.code === 'unauthorized'
            ? 'fail'
            : 'warn',
      message: gatewayCheck.message,
    });
  }

  return {
    ok: checks.every((check) => check.status !== 'fail'),
    checks,
    authHint: providerMetadata.authHint,
  };
}
