import assert from 'node:assert/strict';
import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';

import {
  doctorOpenClawProject,
  getOpenClawProviderMetadata,
  setupOpenClawProject,
} from '../src/openclaw-setup';

test('setupOpenClawProject writes env files, wrapper, and package scripts', async () => {
  const projectDir = await mkdtemp(path.join(os.tmpdir(), 'agent-core-openclaw-init-'));
  const packageJsonFile = path.join(projectDir, 'package.json');

  await writeFile(
    packageJsonFile,
    JSON.stringify(
      {
        name: 'demo-app',
        private: true,
        scripts: {
          dev: 'node server.js',
        },
      },
      null,
      2
    ) + '\n',
    'utf-8'
  );

  const result = await setupOpenClawProject({
    projectDir,
    provider: 'openai-api-key',
    providerSecret: 'sk-test',
  });

  const envContent = await readFile(path.join(projectDir, '.env'), 'utf-8');
  const envExampleContent = await readFile(path.join(projectDir, '.env.example'), 'utf-8');
  const wrapperContent = await readFile(path.join(projectDir, 'run-with-openclaw.mjs'), 'utf-8');
  const packageJsonContent = await readFile(packageJsonFile, 'utf-8');
  const packageJson = JSON.parse(packageJsonContent) as {
    scripts: Record<string, string>;
  };

  assert.match(envContent, /OPENCLAW_URL="http:\/\/127\.0\.0\.1:18789"/);
  assert.match(envContent, /OPENCLAW_GATEWAY_TOKEN="/);
  assert.match(envContent, /OPENCLAW_AGENT_ID="main"/);
  assert.match(envContent, /OPENCLAW_PROVIDER_MODE="openai-api-key"/);
  assert.match(envContent, /OPENAI_API_KEY="sk-test"/);

  assert.match(envExampleContent, /OPENCLAW_GATEWAY_TOKEN=$/m);
  assert.match(envExampleContent, /OPENAI_API_KEY=$/m);

  assert.match(wrapperContent, /Generated by @zootopiafresh\/agent-core openclaw init/);
  assert.match(wrapperContent, /createOpenClawRunner/);

  assert.equal(packageJson.scripts['openclaw:doctor'], 'agent-core openclaw doctor');
  assert.equal(
    packageJson.scripts['dev:with-gateway'],
    'node --env-file=.env ./run-with-openclaw.mjs npm run dev'
  );

  assert.equal(result.provider, 'openai-api-key');
  assert.equal(result.gatewayUrl, 'http://127.0.0.1:18789');
  assert.equal(result.authHint, undefined);
});

test('setupOpenClawProject returns auth hint for auth-based providers', async () => {
  const projectDir = await mkdtemp(path.join(os.tmpdir(), 'agent-core-openclaw-auth-'));
  await writeFile(
    path.join(projectDir, 'package.json'),
    JSON.stringify({ name: 'demo-app', private: true }, null, 2) + '\n',
    'utf-8'
  );

  const result = await setupOpenClawProject({
    projectDir,
    provider: 'openai-codex',
    openclawCmd: 'openclaw',
  });

  assert.equal(result.authHint, 'openclaw models auth login --provider openai-codex');
});

test('doctorOpenClawProject reports healthy local setup shape', async () => {
  const projectDir = await mkdtemp(path.join(os.tmpdir(), 'agent-core-openclaw-doctor-'));
  await writeFile(
    path.join(projectDir, '.env'),
    [
      'OPENCLAW_URL="http://127.0.0.1:19999"',
      'OPENCLAW_GATEWAY_TOKEN="demo-token"',
      'OPENCLAW_AGENT_ID="main"',
      'OPENCLAW_PROVIDER_MODE="openai-api-key"',
      'OPENAI_API_KEY="sk-test"',
    ].join('\n') + '\n',
    'utf-8'
  );
  await writeFile(
    path.join(projectDir, 'run-with-openclaw.mjs'),
    '// Generated by @zootopiafresh/agent-core openclaw init\n',
    'utf-8'
  );

  const result = await doctorOpenClawProject({
    projectDir,
    openclawCmd: 'node',
  });

  const find = (id: string) => result.checks.find((check) => check.id === id);

  assert.equal(result.ok, true);
  assert.equal(find('openclaw-cmd')?.status, 'ok');
  assert.equal(find('env-file')?.status, 'ok');
  assert.equal(find('OPENCLAW_URL')?.status, 'ok');
  assert.equal(find('OPENCLAW_GATEWAY_TOKEN')?.status, 'ok');
  assert.equal(find('OPENAI_API_KEY')?.status, 'ok');
  assert.equal(find('wrapper-file')?.status, 'ok');
});

test('getOpenClawProviderMetadata exposes inline env and auth hints', () => {
  const apiKeyProvider = getOpenClawProviderMetadata('openai-api-key');
  const codexProvider = getOpenClawProviderMetadata('openai-codex', 'openclaw');

  assert.equal(apiKeyProvider.inlineEnvKey, 'OPENAI_API_KEY');
  assert.equal(apiKeyProvider.defaultModel, 'openai/gpt-5.4');
  assert.equal(codexProvider.authHint, 'openclaw models auth login --provider openai-codex');
});
