#!/bin/bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OPENCLAW_CMD="${OPENCLAW_CMD:-$PROJECT_DIR/scripts/openclaw-cli.sh}"
ENV_FILE="${ENV_FILE:-$PROJECT_DIR/.env}"
OPENCLAW_DIR="${OPENCLAW_DIR:-$HOME/.openclaw}"
WORKSPACE_DIR="$OPENCLAW_DIR/workspace"
SKILLS_DIR="$WORKSPACE_DIR/skills"
CONFIG_FILE="$OPENCLAW_DIR/openclaw.json"
COMMON_LIB="$PROJECT_DIR/scripts/lib/openclaw-public.sh"

# shellcheck disable=SC1090
source "$COMMON_LIB"

log() {
  echo "[bootstrap-openclaw] $1"
}

fail() {
  echo "[bootstrap-openclaw] ERROR: $1" >&2
  exit 1
}

upsert_env() {
  upsert_env_file "$ENV_FILE" "$1" "$2"
}

require_var() {
  local name="$1"
  if [ -z "${!name:-}" ]; then
    fail "$name 환경변수가 필요합니다."
  fi
}

if [ -f "$ENV_FILE" ]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi

OPENCLAW_PROJECT_SERVICE_TOKEN="${OPENCLAW_PROJECT_SERVICE_TOKEN:-${!OPENCLAW_PROJECT_SERVICE_TOKEN_ENV_NAME:-}}"

AI_BACKEND="${AI_BACKEND:-openclaw}"
OPENCLAW_PROVIDER_MODE="${OPENCLAW_PROVIDER_MODE:-openai-api-key}"
OPENCLAW_URL="${OPENCLAW_URL:-http://127.0.0.1:18789}"
OPENCLAW_GATEWAY_PORT="${OPENCLAW_GATEWAY_PORT:-18789}"
OPENCLAW_GATEWAY_TOKEN="${OPENCLAW_GATEWAY_TOKEN:-}"
OPENCLAW_PRIMARY_MODEL="${OPENCLAW_PRIMARY_MODEL:-}"
OPENCLAW_AGENT_WORKSPACE="${OPENCLAW_AGENT_WORKSPACE:-$WORKSPACE_DIR}"
INSTALL_OPENCLAW="${INSTALL_OPENCLAW:-1}"
OPENCLAW_PROJECT_SKILL_NAME="${OPENCLAW_PROJECT_SKILL_NAME:-zoopibot-query}"
OPENCLAW_PROJECT_SKILL_SOURCE_DIR="${OPENCLAW_PROJECT_SKILL_SOURCE_DIR:-$PROJECT_DIR/openclaw/skills/$OPENCLAW_PROJECT_SKILL_NAME}"
OPENCLAW_PROJECT_URL_ENV_NAME="${OPENCLAW_PROJECT_URL_ENV_NAME:-ZOOPIBOT_URL}"
OPENCLAW_PROJECT_SERVICE_TOKEN_ENV_NAME="${OPENCLAW_PROJECT_SERVICE_TOKEN_ENV_NAME:-ZOOPIBOT_SERVICE_TOKEN}"
OPENCLAW_PROJECT_PUBLIC_URL="${OPENCLAW_PROJECT_PUBLIC_URL:-${ZOOPIBOT_PUBLIC_URL:-${NEXTAUTH_URL:-http://localhost:3000}}}"
OPENCLAW_PROJECT_SERVICE_TOKEN="${OPENCLAW_PROJECT_SERVICE_TOKEN:-${ZOOPIBOT_SERVICE_TOKEN:-}}"

if [ "$AI_BACKEND" != "openclaw" ]; then
  fail "이 스크립트는 AI_BACKEND=openclaw 환경에서만 사용합니다."
fi

if [ ! -x "$OPENCLAW_CMD" ]; then
  fail "OpenClaw 실행 래퍼가 없습니다: $OPENCLAW_CMD"
fi

if [ "${INSTALL_OPENCLAW}" = "1" ]; then
  log "로컬 openclaw 실행 파일을 확인합니다."
  "$OPENCLAW_CMD" --version >/dev/null
fi

if [ -z "$OPENCLAW_GATEWAY_TOKEN" ]; then
  OPENCLAW_GATEWAY_TOKEN="$(generate_secret)"
  upsert_env OPENCLAW_GATEWAY_TOKEN "$OPENCLAW_GATEWAY_TOKEN"
  log "OPENCLAW_GATEWAY_TOKEN이 없어 새 값을 생성해 .env에 저장했습니다."
fi

if [ -z "$OPENCLAW_PROJECT_SERVICE_TOKEN" ]; then
  OPENCLAW_PROJECT_SERVICE_TOKEN="$(generate_secret)"
  upsert_env "$OPENCLAW_PROJECT_SERVICE_TOKEN_ENV_NAME" "$OPENCLAW_PROJECT_SERVICE_TOKEN"
  log "$OPENCLAW_PROJECT_SERVICE_TOKEN_ENV_NAME 값이 없어 새 값을 생성해 .env에 저장했습니다."
fi

upsert_env AI_BACKEND "$AI_BACKEND"
upsert_env OPENCLAW_URL "$OPENCLAW_URL"
upsert_env OPENCLAW_PROVIDER_MODE "$OPENCLAW_PROVIDER_MODE"

if ! openclaw_provider_metadata "$OPENCLAW_PROVIDER_MODE" "$OPENCLAW_CMD"; then
  fail "지원하지 않는 OPENCLAW_PROVIDER_MODE=${OPENCLAW_PROVIDER_MODE}"
fi

AUTH_HINT="$OPENCLAW_PROVIDER_AUTH_HINT"

if [ -z "$OPENCLAW_PRIMARY_MODEL" ] && [ -n "$OPENCLAW_PROVIDER_DEFAULT_MODEL" ]; then
  OPENCLAW_PRIMARY_MODEL="$OPENCLAW_PROVIDER_DEFAULT_MODEL"
fi

if [ -z "$OPENCLAW_PRIMARY_MODEL" ]; then
  fail "OPENCLAW_PRIMARY_MODEL도 지정해주세요. 예: anthropic/claude-opus-4-1"
fi

if [ -n "$OPENCLAW_PROVIDER_INLINE_ENV_KEY" ]; then
  require_var "$OPENCLAW_PROVIDER_INLINE_ENV_KEY"
fi

upsert_env OPENCLAW_PRIMARY_MODEL "$OPENCLAW_PRIMARY_MODEL"

mkdir -p "$SKILLS_DIR" "$WORKSPACE_DIR"

if install_openclaw_skill "$OPENCLAW_PROJECT_SKILL_SOURCE_DIR" "$SKILLS_DIR" "$OPENCLAW_PROJECT_SKILL_NAME"; then
  log "$OPENCLAW_PROJECT_SKILL_NAME 스킬을 복사했습니다."
fi

PROVIDER_ENV_KEY=""
PROVIDER_ENV_VALUE=""
SKILL_ENTRY_JSON=""

if [ -n "$OPENCLAW_PROVIDER_INLINE_ENV_KEY" ]; then
  PROVIDER_ENV_KEY="$OPENCLAW_PROVIDER_INLINE_ENV_KEY"
  PROVIDER_ENV_VALUE="${!OPENCLAW_PROVIDER_INLINE_ENV_KEY}"
fi

SKILL_ENTRY_JSON="$(build_openclaw_skill_entry_json \
  "$OPENCLAW_PROJECT_SKILL_NAME" \
  "${OPENCLAW_PROJECT_URL_ENV_NAME}=${OPENCLAW_PROJECT_PUBLIC_URL}" \
  "${OPENCLAW_PROJECT_SERVICE_TOKEN_ENV_NAME}=${OPENCLAW_PROJECT_SERVICE_TOKEN}")"

write_openclaw_config \
  "$CONFIG_FILE" \
  "$OPENCLAW_AGENT_WORKSPACE" \
  "$OPENCLAW_PRIMARY_MODEL" \
  "$OPENCLAW_GATEWAY_PORT" \
  "$OPENCLAW_GATEWAY_TOKEN" \
  "$SKILL_ENTRY_JSON" \
  "$PROVIDER_ENV_KEY" \
  "$PROVIDER_ENV_VALUE"

log "OpenClaw 설정 파일을 생성했습니다: $CONFIG_FILE"
log "Provider mode: $OPENCLAW_PROVIDER_MODE"
log "Primary model: $OPENCLAW_PRIMARY_MODEL"
log "Gateway port: $OPENCLAW_GATEWAY_PORT"

if [ -n "$AUTH_HINT" ]; then
  log "추가 인증이 필요합니다: $AUTH_HINT"
fi

log "다음 단계:"
log "  1) yarn dev"
log "  2) 운영 빌드 실행 시 yarn start"
